=== Yuno-Torushie/Algorithme-fin/XML_TD3a_SAX_EXO1/bin/exo2/wg.dtd
<!ELEMENT gdt  (expose*)>
<!ATTLIST gdt 
	  month CDATA #REQUIRED 
	  year CDATA #REQUIRED>
<!ELEMENT expose  (comment?, (speaker, title, time, salle)?)>
<!ATTLIST expose day CDATA #REQUIRED>
<!ELEMENT comment      (#PCDATA)>
<!ELEMENT speaker       (#PCDATA)>
<!ELEMENT title       (#PCDATA)>
<!ELEMENT time       (#PCDATA)>
<!ELEMENT salle       (#PCDATA)>
<!ENTITY nbsp "&#160;">

=== Yuno-Torushie/Algorithme-fin/XML_TD3a_SAX_EXO1/bin/exo2/wg.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE gdt SYSTEM "wg.dtd">
<gdt month="February" year="2017">
  <expose day="5">
    <speaker>Nicolas Baudru</speaker>
    <title>Netcharts et HMSC</title>
    <time>12h45</time>
    <salle>102</salle>
  </expose>

  <expose day="12"> 
    <comment>Exposé proposé par François Denis, équipe BDA</comment>
    <speaker>Liva Ralaivola</speaker>
    <title>apprentissage statistique, noyaux et applications à la
    bio-informatique</title>  
    <time>14h</time>
    <salle>104</salle>
    <!-- Commentaire incroyable -->
  </expose>

  <expose day="19"> 
    <comment>pas de groupe de travail</comment>
  </expose>
 
  <expose day="26"> <!-- Amazing comment -->
    <speaker>Pedro d'Argenio</speaker>
    <title>Secure Information Flow by Self-Composition</title>  
    <time>12h45</time>
    <salle>102&nbsp;</salle>
  </expose><?PI final ?>
</gdt>
